### PR TITLE
add tullia tasks and cicero action for CI

### PR DESCRIPTION
**Pull request by dermetfan**
Also purified nix evaluation of hydra jobs.

### CODE REVIEW

**Comment by piotr-iohk** [comment]
There is this cicero job failing https://cicero.ci.iog.io/run/940d28a9-711e-408b-8ccb-7f7388ccf7bb, I guess this needs to be addressed before merging @dermetfan?

**Comment by dermetfan** [comment]
@piotr-iohk I think no. It fails because the nix build is failing, which is what CI is supposed to report, so CI is working.

**Comment by piotr-iohk** [comment]
@paweljakubas @HeinrichApfelmus do you know why is this job failing and how to fix it? https://cicero.ci.iog.io/run/940d28a9-711e-408b-8ccb-7f7388ccf7bb

**Comment by HeinrichApfelmus** [comment]
> do you know why is this job failing and how to fix it?

Unfortunately, I am unable to tell from the Cicero UI whether the job is failing or not. I see the following items:

* "General information" > "Status | succeeded"
* "Facts" > "55ef357e-84d5-40f1-b94c-bd9c87e8e06c" > `{ "ok": true, …}`
* "Task groups" > "nomad" > "General information" > "Failed | false"
* "Task groups" > "nomad" > "General information" > "State | dead"
* "Task groups" > "nomad" > "Task log" > second-to last line: `error: builder for '/nix/store/yxnam041qfml8hc0q1ziygn9hgjkaqad-cardano-addresses-demo-js-3.12.0.drv' failed with exit code 1`

How do I make heads or tails of this?

**Comment by dermetfan** [comment]
@HeinrichApfelmus

> "General information" > "Status | succeeded"
> "Facts" > "55ef357e-84d5-40f1-b94c-bd9c87e8e06c" > `{ "ok": true, …}`
> "Task groups" > "nomad" > "General information" > "Failed | false"

Unfortunately this status is often wrong (since we switched to the podman driver iirc). We are aware of this and there's an open issue.

Truth is that `nix build .#hydraJobs.x86_64-linux.packages.x86_64-linux.cardano-addresses-demo-js` failed:

```
Building .#hydraJobs.x86_64-linux.packages.x86_64-linux.cardano-addresses-demo-js…
 drv: /nix/store/yxnam041qfml8hc0q1ziygn9hgjkaqad-cardano-addresses-demo-js-3.12.0.drv
 out: /nix/store/p36paw07gwwc4nz0kafy4pvwh2brvpnx-cardano-addresses-demo-js-3.12.0
...
cardano-addresses-demo-js> dist directory is missing - you need to 'npm run build' first
error: builder for '/nix/store/yxnam041qfml8hc0q1ziygn9hgjkaqad-cardano-addresses-demo-js-3.12.0.drv' failed with exit code 1
```

**Comment by HeinrichApfelmus** [comment]
> Unfortunately this status is often wrong (since we switched to the podman driver iirc). We are aware of this and there's an open issue.

@dermetfan thanks. While we're at it: Could you also change the status description "Failed: false" to "Success: true"? Reading the double negative is very confusing.

**Comment by HeinrichApfelmus** [comment]
> do you know why is this job failing and how to fix it?

@piotr-iohk I have no idea. Apparently, the `nix` expression for `cardano-addresses-demo-js` fails to build. There seems to be something wrong with the JavaScript parts, `npm` complains that `you need to 'npm run build' first`.

**Comment by angerman** [comment]
As cicero is gone, I think we can drop this.

**Pull request closed without merging**
