### PR TITLE
Update index state.  Use hw-aeson from hackage.

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by paweljakubas** [comment]
hi @newhoggy This PR is not valid anymore, correct?

**Comment by paweljakubas** [comment]
hi @newhoggy 
After rebasing I see the following problem in TypeScript NPM Package check 
```
error: Unknown index-state 2022-08-15T00:00:00Z, the latest index-state I know about is 2022-04-05T00:00:00Z. You may need to update to a newer hackage.nix.
```

**Comment by Unisay** [comment]
`nix develop` is broken for me:
```
 nix develop
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'ghc-shell-for-packages'
         whose name attribute is located at /nix/store/qc0cdv66gcsq5l529qxsy6fdxyhj4zqr-source/pkgs/stdenv/generic/make-derivation.nix:303:7

       … while evaluating attribute 'nativeBuildInputs' of derivation 'ghc-shell-for-packages'

         at /nix/store/qc0cdv66gcsq5l529qxsy6fdxyhj4zqr-source/pkgs/stdenv/generic/make-derivation.nix:347:7:

          346|       depsBuildBuild              = lib.elemAt (lib.elemAt dependencies 0) 0;
          347|       nativeBuildInputs           = lib.elemAt (lib.elemAt dependencies 0) 1;
             |       ^
          348|       depsBuildTarget             = lib.elemAt (lib.elemAt dependencies 0) 2;

       error: builder for '/nix/store/wf9nzpqnx0gg7wajd0qlny5ljjw37yqz-haskell-language-server-plan-to-nix-pkgs.drv' failed with exit code 1;
       last 10 log lines:
       > hls-fourmolu-plugin-1.0.2.0, hls-fourmolu-plugin-1.0.1.2,
       > hls-fourmolu-plugin-1.0.1.1, hls-fourmolu-plugin-1.0.0.2,
       > hls-fourmolu-plugin-1.0.0.1, hls-fourmolu-plugin-1.0.0.0 (conflict:
       > haskell-language-server +fourmolu => hls-fourmolu-plugin==2.4.0.0)
       > [__2] fail (backjumping, conflict set: haskell-language-server,
       > hls-fourmolu-plugin, haskell-language-server:fourmolu)
       > After searching the rest of the dependency tree exhaustively, these were the
       > goals I've had most trouble fulfilling: haskell-language-server,
       > haskell-language-server:fourmolu, hls-fourmolu-plugin
       > )
       For full logs, run 'nix log /nix/store/wf9nzpqnx0gg7wajd0qlny5ljjw37yqz-haskell-language-server-plan-to-nix-pkgs.
    ```

**Comment by HeinrichApfelmus** [comment]
The `TypeScript NPM` step fails due to a compilation error when compiling `cborg-0.2.8.0` with the `--ghcjs` flag.

```
Preprocessing library for cborg-0.2.8.0..
Building library for cborg-0.2.8.0..
Configure flags:
--prefix=/nix/store/22dmll188lbz4prv8bvd3nr189dkczyn-OneTuple-lib-OneTuple-0.3.1
lib:OneTuple --package-db=clear
--package-db=/build/tmp.0XWHIPv80o/lib/js-unknown-ghcjs-ghc-8.10.7/package.conf.d
--exact-configuration
--dependency=base-orphans=base-orphans-0.8.7-68gGt71vpOZ5uwbcNbxwhZ --dependency=hashable
=hashable-1.4.2.0-GxxUVWGGZcoFRQWxNr360V
--dependency=base-orphans=base-orphans-0.8.7-68gGt71vpOZ5uwbcNbxwhZ
--dependency=bytestring=bytestring-0.10.12.0-A1EizoKtfkUxRIgN0VmIs
--dependency=containers=containers-0.6.5.1-Jb3F8jbyqRBHMHVa9Whe7M
--dependency=data-array-byte=data-array-byte-0.1.0.1-JHCJRujc0FRAdK1gEZ8gQC
--dependency=filepath=filepath-1.4.2.1-59K9q30pCxYEXHuiiIsQvI
--dependency=text=text-1.2.4.1-Hktns1tWh1j2vlgIoSVYTC
--dependency=binary=binary-0.8.8.0-8geveWiewY98oMa1Q4NvzB
--dependency=array=array-0.5.4.0-BY9BworFlmHJapi9znoqNH
--dependency=base=base-4.14.3.0-D0KSEBqJsPj2jV088Mzd5k
--dependency=deepseq=deepseq-1.4.4.0-1l24lJnqQnGEBnHHreMAq3
--dependency=ghc-boot-th=ghc-boot-th-8.10.7-FQtGTtjFMOPJdcMgIgVdDb
--dependency=ghc-prim=ghc-prim-0.6.1-7Cgvu6TLhQr9ma5lroclUe
--dependency=ghcjs-prim=ghcjs-prim-0.1.1.0-HZUIQ7BTQrzF5jVh07mbue
--dependency=ghcjs-th=ghcjs-th-0.1.0.0-JdGbYrK1CstBZz9Zn9tGjt
--dependency=integer-gmp=integer-gmp-1.0.3.0-63uAhGZ1DDrBtoXgnrDqDZ
--dependency=pretty=pretty-1.1.3.6-GAhFbJ44WwF1NMuTt9nXuU --dependency=rts=rts
--dependency=template-haskell=template-haskell-2.16.0.0-ILUM7zMBAmY2f0T80iaLZe
--with-ghc=js-unknown-ghcjs-ghc --with-ghc-pkg=js-unknown-ghcjs-ghc-pkg
--with-hsc2hs=js-unknown-ghcjs-hsc2hs
--with-gcc=/nix/store/n2k3pi2kdfmigks71vljy4c8birfsd1q-emscripten-3.1.24/bin/emcc
--with-ld=/nix/store/n2k3pi2kdfmigks71vljy4c8birfsd1q-emscripten-3.1.24/bin/emcc
--disable-executable-stripping --disable-library-stripping --disable-library-profiling
--disable-profiling --enable-static --disable-shared --disable-executable-dynamic
--disable-coverage --disable-library-for-ghci
--datadir=/nix/store/xxpzic7kk9b88v05prcmwdpg97snpppx-OneTuple-lib-OneTuple-0.3.1-data/sh
are/js-unknown-ghcjs-ghc-8.10.7 --hsc2hs-option=--cross-compile --ghcjs
--with-ghcjs=js-unknown-ghcjs-ghc --with-ghcjs-pkg=js-unknown-ghcjs-ghc-pkg
--with-gcc=/nix/store/lszbak7w3k1jmx3cm3qb2qzillsib71v-emscripten-3.1.24/bin/emcc
Configuring library for OneTuple-0.3.1..
[ 1 of 14] Compiling Codec.CBOR.ByteArray.Internal ( src/Codec/CBOR/ByteArray/Internal.hs, dist/build/Codec/CBOR/ByteArray/Internal.js_o )
[]
"OK. Lib"
building
"dist/build/emcc/lib.js doesn't exist!"
Preprocessing library for OneTuple-0.3.1..
Building library for OneTuple-0.3.1..
[ 2 of 14] Compiling Codec.CBOR.ByteArray.Sliced ( src/Codec/CBOR/ByteArray/Sliced.hs, dist/build/Codec/CBOR/ByteArray/Sliced.js_o )
[1 of 3] Compiling Data.Tuple.Solo  ( src/Data/Tuple/Solo.hs, dist/build/Data/Tuple/Solo.js_o )
[ 3 of 14] Compiling Codec.CBOR.ByteArray ( src/Codec/CBOR/ByteArray.hs, dist/build/Codec/CBOR/ByteArray.js_o )
[ 4 of 14] Compiling Codec.CBOR.Decoding ( src/Codec/CBOR/Decoding.hs, dist/build/Codec/CBOR/Decoding.js_o )

src/Codec/CBOR/Decoding.hs:346:19: error:
    • Couldn't match expected type ‘Int64#’ with actual type ‘Int#’
    • In the first argument of ‘I64#’, namely ‘n’
      In the expression: I64# n
      In an equation for ‘toInt64’: toInt64 n = I64# n
    |
346 | toInt64  n = I64# n
    |                   ^

src/Codec/CBOR/Decoding.hs:350:19: error:
    • Couldn't match expected type ‘Word64#’ with actual type ‘Word#’
    • In the first argument of ‘W64#’, namely ‘n’
      In the expression: W64# n
      In an equation for ‘toWord64’: toWord64 n = W64# n
    |
350 | toWord64 n = W64# n
    |    
[…]
```

Looks like GHCJS makes explicit some assumptions about the size of `Int` and `Word`.

**Comment by Crypto2099** [comment]
Deprecated by: https://github.com/IntersectMBO/cardano-addresses/pull/231

Can be closed?

**Comment by paweljakubas** [comment]
not valid anymore

**Pull request closed without merging**
