### PR TITLE
Remove dependency on hjsonschema

### PR DESCRIPTION
**Pull request by abailly**
This is needed for #285

### CODE REVIEW

**Review by erikd — CHANGES_REQUESTED** [review]
@abailly Looks good, but would like to see a minimal diff. There seem to have been a bunch un-needed of formatting changes in this PR.

**Comment by abailly** [comment]
My bad, I have autoformatting on with fourmolu.

**Review by erikd — APPROVED** [review]
Looking good. Thanks.

**Comment by erikd** [comment]
@paweljakubas Would appreciate it if you could also review.

**Review by paweljakubas — APPROVED** [review]
looks reasonable and good to me

**Pull request merged**
