### PR TITLE
Allow building with ghc-9.2

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Comment by paweljakubas** [comment]
hi @angerman it seems there are iohk-nix and haskell.nix problems in CI. Any chance you could look at them?

**Comment by paweljakubas** [comment]
1. when building TypeScript NPM Package
```
unpacking source archive /build/dc03db8b910aabba75931e524368df14eb9f7852.tar.gz
error:
       … while evaluating the attribute 'shell'

         at /home/runner/work/cardano-addresses/cardano-addresses/jsapi/default.nix:8:3:

            7|
            8|   shell = cardano-addresses-js-shell;
             |   ^
            9|

       … while evaluating the attribute 'packages.x86_64-linux'

         at /nix/store/ddm4xvz1gbbd1hbjaxmfsbzd6gzyglz2-source/default.nix:74:51:

           73|             {
           74|               ${key} = (attrs.${key} or { }) // { ${system} = ret.${key}; };
             |                                                   ^
           75|             }

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: list index 0 is out of bounds

       at «none»:0: (source not available)
Error: Process completed with exit code 1.
```

**Comment by Unisay** [comment]
I have this error when starting `nix develop` shell on this branch:

```
 yura@fractal  ~/projects/cardano-addresses   erikd/ghc-9.2  nix develop                          
error:
       … while evaluating the attribute 'packages'

         at /nix/store/w34a3j05pqqmsk4y3vbpzbf4klhacx03-source/lib/attrsets.nix:366:7:

          365|       inherit name;
          366|       value = f name (catAttrs name sets);
             |       ^
          367|     }) names);

       … while evaluating a branch condition

         at /nix/store/w34a3j05pqqmsk4y3vbpzbf4klhacx03-source/lib/attrsets.nix:419:9:

          418|         let here = attrPath ++ [n]; in
          419|         if tail values == []
             |         ^
          420|         || pred here (head (tail values)) (head values) then

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: builder for '/nix/store/cbkqf7pp8q54k7fp2fsrhkb371d6r1ni-haskell-project-plan-to-nix-pkgs.drv' failed with exit code 1;
       last 10 log lines:
       > http-types-0.2.0, http-types-0.1.1, http-types-0.1 (has the same
       > characteristics that caused the previous version to fail: excludes
       > 'bytestring' version 0.11.4.0)
       > [__5] fail (backjumping, conflict set: bytestring, http-types, jsaddle-warp)
       > After searching the rest of the dependency tree exhaustively, these were the
       > goals I've had most trouble fulfilling: bytestring, jsaddle, jsaddle-warp,
       > http-types, cardano-addresses-jsapi, cardano-addresses-jsapi:test,
       > cardano-addresses
       > Try running with --minimize-conflict-set to improve the error message.
       > )
       For full logs, run 'nix log /nix/store/cbkqf7pp8q54k7fp2fsrhkb371d6r1ni-haskell-project-plan-to-nix-pkgs.drv'.
   ```
   ```
   Run 'cabal update' to get the latest list of available packages.
Warning: Requested index-state 2023-01-14T00:00:00Z is newer than
'hackage.haskell.org'! Falling back to older state (2023-01-13T21:42:37Z).
Resolving dependencies...
make-install-plan: dieVerbatim: user error (Error: make-install-plan: Could not resolve dependencies:
[__0] trying: cardano-addresses-3.12.0 (user goal)
[__1] next goal: bytestring (dependency of cardano-addresses)
[__1] rejecting: bytestring-0.10.12.0/installed-0.10.12.0 (constraint from
project config /build/tmp.wYPNrhXVAP/cabal.project requires >=0.11.4)
[__1] trying: bytestring-0.11.4.0
[__2] trying: cardano-addresses-jsapi-3.12.0 (user goal)
[__3] trying: cardano-addresses-jsapi:*test
[__4] next goal: jsaddle-warp (dependency of cardano-addresses-jsapi *test)
[__4] rejecting: jsaddle-warp-0.9.8.2 (conflict: bytestring==0.11.4.0,
jsaddle-warp => bytestring>=0.10.6.0 && <0.11)
[__4] skipping: jsaddle-warp-0.9.8.0, jsaddle-warp-0.9.7.1,
jsaddle-warp-0.9.7.0, jsaddle-warp-0.9.6.0, jsaddle-warp-0.9.5.0,
jsaddle-warp-0.9.4.0, jsaddle-warp-0.9.3.0, jsaddle-warp-0.9.2.0,
jsaddle-warp-0.9.1.0 (has the same characteristics that caused the previous
version to fail: excludes 'bytestring' version 0.11.4.0)
[__4] trying: jsaddle-warp-0.9.0.0
[__5] next goal: http-types (dependency of jsaddle-warp)
[__5] rejecting: http-types-0.12.3 (conflict: jsaddle-warp =>
http-types>=0.8.6 && <0.10)
[__5] skipping: http-types-0.12.2, http-types-0.12.1, http-types-0.12,
http-types-0.11, http-types-0.10 (has the same characteristics that caused the
previous version to fail: excluded by constraint '>=0.8.6 && <0.10' from
'jsaddle-warp')
[__5] rejecting: http-types-0.9.1 (conflict: bytestring==0.11.4.0, http-types
=> bytestring>=0.9.1.5 && <0.11)
[__5] skipping: http-types-0.9, http-types-0.8.6, http-types-0.8.5,
http-types-0.8.4, http-types-0.8.3, http-types-0.8.2, http-types-0.8.1,
http-types-0.8.0, http-types-0.7.3.0.1, http-types-0.7.3, http-types-0.7.2,
http-types-0.7.1, http-types-0.7.0, http-types-0.6.11, http-types-0.6.10,
http-types-0.6.9, http-types-0.6.8, http-types-0.6.7, http-types-0.6.6,
http-types-0.6.5.1, http-types-0.6.5, http-types-0.6.4, http-types-0.6.3,
http-types-0.6.2, http-types-0.6.1, http-types-0.6.0.1, http-types-0.6.0,
http-types-0.5.3, http-types-0.5.2, http-types-0.5.1, http-types-0.5,
http-types-0.4.1, http-types-0.4.0, http-types-0.3.1, http-types-0.3.0,
http-types-0.2.0, http-types-0.1.1, http-types-0.1 (has the same
characteristics that caused the previous version to fail: excludes
'bytestring' version 0.11.4.0)
[__5] fail (backjumping, conflict set: bytestring, http-types, jsaddle-warp)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: bytestring, jsaddle, jsaddle-warp,
http-types, cardano-addresses-jsapi, cardano-addresses-jsapi:test,
cardano-addresses
Try running with --minimize-conflict-set to improve the error message.
)
```

**Comment by angerman** [comment]
Superceeded by #231

**Pull request closed without merging**
